### ISSUE TITLE
Any examples for generating a gninatypes file?

### ISSUE THREAD

**Issue by HyungSik-Jo** [gnina/scripts#46]
I have completed the libmolgrid / gnina settings to calculate the binding affinity of the data I have.

The tests of train.py, which create a new model with existing data, and predict.py, which make predictions, have been completed.
(crossdocked2020 dataset and default2018 model )

However, it cannot be predicted with the data I have.

My data :
protein.pdb
protein_rec.pdb
molecule.sdf

protein is the total protein structure information data received from the PDB, protein_rec is data extracted only from the binding site, and 3D information of the molecule is included in sdf.

Any examples or explanations on how to change these data to .gninatypes ?

**Comment by HyungSik-Jo** [comment]
I stumbled across the phrase in an earlier issue that says you don't need to use gninatypes .

The above question turned out to be a format problem with input types.

`<label> <pK> <RMSD to crystal> <Receptor> <Ligand> # <Autodock Vina score>`
https://github.com/gnina/models/tree/master/data/CrossDocked2020

If you follow the format of the page and run it, it runs normally!

However, the label pK RMSD value does not exist by default in my data.

In this case, how do I set it up and run it?

If 0 0 0 is entered as an arbitrary value, it is executed, but a warning occurs.

```
Warning: only one unique label
Warning: no true affinities, setting rmsd=-999.0
```

**Comment by dkoes** [comment]
You need to change your model to not expect the rmsd field (has_rmsd=false)

**Comment by HyungSik-Jo** [comment]
@dkoes Thanks for your reply.

I proceeded as you commented, but the same warning occurs.

Removed rmsd_true from the top of the caffe model and changed it to has_rmsd=false.

input.types was entered as `<label> <pK> <Receptor> <Ligand> = 0 0 ./data/protein_rec.pdb ./data/molecule.sdf`

Attach the last 3 lines of the output result.
```
0.108353 4.438304 | 0 0 ./data/protein_rec.pdb ./data/molecule.sdf 
# AUC 1.000000
# rmsd -999.000000
```

Can I trust that the following results were printed normally?

**Comment by dkoes** [comment]
The predict.py scripts assumes the existence of an rmsd field.  You will have to modify the scripts accordingly to deal with its absense.

**Comment by JonasLi-19** [comment]
Maybe just use the script train.py with --test_only will solve this problem?  

Could you please tell us the difference between using "train.py --test_only" and "predocy.py"? (input demands, output format) 

Thanks

**Comment by francoep** [comment]
You need the caffe .model file formatted correctly. If you do not have the RMSD column, both the Training and Testing net sections of the model file need to have has_rmsd = False.

train.py --test_only will give you nonsense unless you also specify --weights, since it will evaluate the defined test set with random initialized weights.

predict.py requires you to have a correctly defined caffe model file with TESTFILE that is unshuffled and unbalanced, the weights for the network, and the input .types file to perform the prediction on.

Your input .types file has to be formatted correctly to go with your caffe model file.

I would not recommend using train.py --test_only, it in practice could work, but would not give your outputs in an easy to find manner. predict.py  lets you name your output files so they are much easier to determine/find and can be different from the names of the model & weights.

From the warnings raised, your input types files only have one label -- first column is all 0's or all 1's, which means the AUC was not calculated since there is nothing to compute (and the 1.000 output).  Then, since your true binding affinities are all 0, the rmsd calculation was also not performed, hence the -999.

Depending on what you are meaning to do, this could be fine or could not be. The output file above those two lines will be as follows:  "pose score" "predicted binding affinity" | "typesfile line"
